apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '5.1.0'
    chart: contour
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true