apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      parameters:
       - name: alertmanager.enabled	
         value: "false"
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '6.1.4'
    chart: kube-prometheus
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true