---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/warroyo/cs-argo
    path: addons/sealedsecrets
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true